WIP

diff --git a/.github/workflows/ci-build.yaml b/.github/workflows/ci-build.yaml
--- a/.github/workflows/ci-build.yaml
+++ b/.github/workflows/ci-build.yaml
@@ -93,7 +93,7 @@ env:
 
 jobs:
   pre-build-checks:
-    if: github.repository == 'apache/camel-quarkus'
+    if: github.repository == 'jamesnetherton/camel-quarkus'
     runs-on: ubuntu-latest
     outputs:
       continue-build: ${{ steps.pre-build-checks.outputs.continue-build }}
@@ -626,79 +626,79 @@ jobs:
         with:
           test-report-xml-base-dir: integration-tests
 
-  examples-tests:
-    name: Examples Tests - ${{matrix.name}}
-    needs: initial-mvn-install
-    runs-on: ubuntu-latest
-    if: github.event_name != 'pull_request' || !contains(github.event.pull_request.labels.*.name, 'JVM')
-    strategy:
-      fail-fast: false
-      matrix: ${{ fromJson(needs.initial-mvn-install.outputs.examples-matrix) }}
-    steps:
-      - name: Checkout
-        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
-      - name: Set up JDK 17
-        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
-        with:
-          distribution: 'temurin'
-          java-version: '17'
-      - name: Download Maven Repo
-        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
-        with:
-          name: maven-repo
-          path: ..
-      - name: Extract Maven Repo
-        shell: bash
-        run: |
-          df -h /
-          tar -xzf ../maven-repo.tgz -C ~
-          rm -f ../maven-repo.tgz
-          df -h /
-      - name: set CQ_VERSION
-        run: echo "CQ_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout -N)" >> $GITHUB_ENV
-      - name: clone and verify examples
-        env:
-          EXAMPLE_MODULES: ${{matrix.examples}}
-        shell: '/usr/bin/bash {0}'
-        run: |
-          EXAMPLES_BRANCH="camel-quarkus-main"
-
-          if [[ ${GITHUB_REF_NAME} =~ [0-9]+.[0-9]+.x ]]; then
-              EXAMPLES_BRANCH=${GITHUB_REF_NAME}
-          elif [[ ${GITHUB_BASE_REF} =~ [0-9]+.[0-9]+.x ]]; then
-              EXAMPLES_BRANCH=${GITHUB_BASE_REF}
-          fi
-
-          git clone --depth 1 --branch ${EXAMPLES_BRANCH} https://github.com/apache/camel-quarkus-examples.git \
-            && cd camel-quarkus-examples \
-            && echo "Current Examples commit:" $(git rev-parse HEAD) \
-            && ./mvnw ${CQ_MAVEN_ARGS} ${BRANCH_OPTIONS} org.l2x6.cq:cq-maven-plugin:2.10.0:examples-set-platform -Dcq.camel-quarkus.version=${CQ_VERSION}
-
-          BUILD_FAILURES=()
-
-          for MODULE in ${EXAMPLE_MODULES//,/ }; do
-            cd ${MODULE}
-
-            ../mvnw ${CQ_MAVEN_ARGS} clean verify \
-              -Dformatter.skip -Dimpsort.skip \
-              -Dquarkus.native.builder-image.pull=missing \
-              -Pnative,docker,ci
-
-            if [[ $? -ne 0 ]]; then
-              BUILD_FAILURES[${#BUILD_FAILURES[@]}]=${MODULE}
-            fi
-
-            cd -
-          done
-
-          if [[ ${#BUILD_FAILURES[@]} -gt 0 ]]; then
-            echo -e "\nBuild errors were encountered in the following projects:\n"
-            for FAILURE in ${BUILD_FAILURES[@]}; do
-                echo "* ${FAILURE}"
-            done
-            echo -e "\nCheck build logs for further information."
-            exit 1
-          fi
-      - name: Report test failures
-        uses: ./.github/actions/test-summary-report
-        if: ${{ failure() }}
+#  examples-tests:
+#    name: Examples Tests - ${{matrix.name}}
+#    needs: initial-mvn-install
+#    runs-on: ubuntu-latest
+#    if: github.event_name != 'pull_request' || !contains(github.event.pull_request.labels.*.name, 'JVM')
+#    strategy:
+#      fail-fast: false
+#      matrix: ${{ fromJson(needs.initial-mvn-install.outputs.examples-matrix) }}
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+#      - name: Set up JDK 17
+#        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
+#        with:
+#          distribution: 'temurin'
+#          java-version: '17'
+#      - name: Download Maven Repo
+#        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
+#        with:
+#          name: maven-repo
+#          path: ..
+#      - name: Extract Maven Repo
+#        shell: bash
+#        run: |
+#          df -h /
+#          tar -xzf ../maven-repo.tgz -C ~
+#          rm -f ../maven-repo.tgz
+#          df -h /
+#      - name: set CQ_VERSION
+#        run: echo "CQ_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout -N)" >> $GITHUB_ENV
+#      - name: clone and verify examples
+#        env:
+#          EXAMPLE_MODULES: ${{matrix.examples}}
+#        shell: '/usr/bin/bash {0}'
+#        run: |
+#          EXAMPLES_BRANCH="camel-quarkus-main"
+#
+#          if [[ ${GITHUB_REF_NAME} =~ [0-9]+.[0-9]+.x ]]; then
+#              EXAMPLES_BRANCH=${GITHUB_REF_NAME}
+#          elif [[ ${GITHUB_BASE_REF} =~ [0-9]+.[0-9]+.x ]]; then
+#              EXAMPLES_BRANCH=${GITHUB_BASE_REF}
+#          fi
+#
+#          git clone --depth 1 --branch ${EXAMPLES_BRANCH} https://github.com/apache/camel-quarkus-examples.git \
+#            && cd camel-quarkus-examples \
+#            && echo "Current Examples commit:" $(git rev-parse HEAD) \
+#            && ./mvnw ${CQ_MAVEN_ARGS} ${BRANCH_OPTIONS} org.l2x6.cq:cq-maven-plugin:2.10.0:examples-set-platform -Dcq.camel-quarkus.version=${CQ_VERSION}
+#
+#          BUILD_FAILURES=()
+#
+#          for MODULE in ${EXAMPLE_MODULES//,/ }; do
+#            cd ${MODULE}
+#
+#            ../mvnw ${CQ_MAVEN_ARGS} clean verify \
+#              -Dformatter.skip -Dimpsort.skip \
+#              -Dquarkus.native.builder-image.pull=missing \
+#              -Pnative,docker,ci
+#
+#            if [[ $? -ne 0 ]]; then
+#              BUILD_FAILURES[${#BUILD_FAILURES[@]}]=${MODULE}
+#            fi
+#
+#            cd -
+#          done
+#
+#          if [[ ${#BUILD_FAILURES[@]} -gt 0 ]]; then
+#            echo -e "\nBuild errors were encountered in the following projects:\n"
+#            for FAILURE in ${BUILD_FAILURES[@]}; do
+#                echo "* ${FAILURE}"
+#            done
+#            echo -e "\nCheck build logs for further information."
+#            exit 1
+#          fi
+#      - name: Report test failures
+#        uses: ./.github/actions/test-summary-report
+#        if: ${{ failure() }}
